import NavigationBar from "@/components/NavigationBar";
import "./globals.css";
import type { Metadata } from "next";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="">
                <NavigationBar />
                {children}
                <Footer />
                {/* {children}
                <Footer /> */}
            </body>
        </html>
    );
}
